In [1]:
# preamble

import numpy as np
from datascience import *
import matplotlib
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import pandas as pd
import sqlalchemy

In [2]:
# raw data

c19_df = pd.read_csv("https://raw.githubusercontent.com/jamesyoung4/chi_covid_analysis/main/data/Chi-C19-Data.csv")
vax_df = pd.read_csv("https://raw.githubusercontent.com/jamesyoung4/chi_covid_analysis/main/data/Chi-Vax-Data.csv")
crime_df = pd.read_csv("https://raw.githubusercontent.com/jamesyoung4/chi_covid_analysis/main/data/Chi-Crime-Data.csv")

In [3]:
# database

sqlite_uri = "sqlite:///analysis.db"
sqlite_engine = sqlalchemy.create_engine(sqlite_uri)

temp = c19_df.to_sql('c19', con=sqlite_engine)
temp = vax_df.to_sql('vax', con=sqlite_engine)
temp = crime_df.to_sql('crime', con=sqlite_engine)

In [4]:
sql_expr = """
SELECT *
FROM c19
"""

pd.read_sql(sql_expr, sqlite_engine)

,index,ZIP Code,Week Number,Week Start,Week End,Cases - Weekly,Cases - Cumulative,Case Rate - Weekly,Case Rate - Cumulative,Tests - Weekly,...,Test Rate - Cumulative,Percent Tested Positive - Weekly,Percent Tested Positive - Cumulative,Deaths - Weekly,Deaths - Cumulative,Death Rate - Weekly,Death Rate - Cumulative,Population,Row ID,ZIP Code Location
0,0,60603,10,03/01/2020,03/07/2020,NaN,NaN,NaN,NaN,0.0,...,0.0,0.0,0.0,0,0,0.0,0.0,1174,60603-2020-10,POINT (-87.625473 41.880112)
1,1,60603,11,03/08/2020,03/14/2020,NaN,NaN,NaN,NaN,0.0,...,0.0,0.0,0.0,0,0,0.0,0.0,1174,60603-2020-11,POINT (-87.625473 41.880112)
2,2,60603,12,03/15/2020,03/21/2020,NaN,NaN,NaN,NaN,1.0,...,85.2,0.0,0.0,0,0,0.0,0.0,1174,60603-2020-12,POINT (-87.625473 41.880112)
3,3,60603,13,03/22/2020,03/28/2020,NaN,NaN,NaN,NaN,3.0,...,340.7,0.0,0.0,0,0,0.0,0.0,1174,60603-2020-13,POINT (-87.625473 41.880112)
4,4,60603,14,03/29/2020,04/04/2020,NaN,NaN,NaN,NaN,6.0,...,851.8,0.0,0.0,0,0,0.0,0.0,1174,60603-2020-14,POINT (-87.625473 41.880112)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,2995,60620,22,05/24/2020,05/30/2020,53.0,1065.0,78.0,1564.0,892.0,...,9276.6,0.1,0.2,1,66,1.5,96.9,68096,60620-2020-22,POINT (-87.651656 41.740873)
2996,2996,60630,35,08/23/2020,08/29/2020,51.0,1162.0,89.0,2026.4,991.0,...,25334.8,0.1,0.1,1,63,1.7,109.9,57344,60630-2020-35,POINT (-87.759611 41.971261)
2997,2997,60640,3,01/17/2021,01/23/2021,81.0,3792.0,116.0,5439.3,3364.0,...,115388.4,0.0,0.0,3,138,4.3,197.9,69715,60640-2021-3,POINT (-87.662232 41.971888)
2998,2998,60666,45,11/01/2020,11/07/2020,NaN,NaN,NaN,NaN,0.0,...,0.0,0.0,0.0,0,0,0.0,0.0,0,60666-2020-45,POINT (-87.896371 41.979511)
2999,2999,60621,16,04/12/2020,04/18/2020,75.0,218.0,258.0,750.6,168.0,...,2014.3,0.4,0.4,3,9,10.3,31.0,29042,60621-2020-16,POINT (-87.638812 41.776931)

In [5]:
sql_expr = """
SELECT *
FROM vax
"""

pd.read_sql(sql_expr, sqlite_engine)

,index,Date,Total Doses - Daily,Total Doses - Cumulative,1st Dose - Daily,1st Dose - Cumulative,1st Dose - Percent Population,Vaccine Series Completed - Daily,Vaccine Series Completed - Cumulative,Vaccine Series Completed - Percent Population,...,Vaccine Series Completed - Daily - Age 60-69,Vaccine Series Completed - Daily - Age 70-79,Vaccine Series Completed - Daily - Age 80+,Vaccine Series Completed - Daily - Age 18+,Vaccine Series Completed - Daily - Age 65+,Vaccine Series Completed - Daily - Age 75+,Vaccine Series Completed - Daily - Unknown Age,Vaccine Series Completed - Daily - Female,Vaccine Series Completed - Daily - Male,Vaccine Series Completed - Daily - Unknown Gender
0,0,02/15/2021,4327,356643,3678,264025,0.098,649,92618,0.034,...,99,141,48,649,263,95,0,383,262,4
1,1,12/15/2020,4,4,4,4,0.000,0,0,0.000,...,0,0,0,0,0,0,0,0,0,0
2,2,12/16/2020,148,152,148,152,0.000,0,0,0.000,...,0,0,0,0,0,0,0,0,0,0
3,3,12/17/2020,1989,2141,1989,2141,0.001,0,0,0.000,...,0,0,0,0,0,0,0,0,0,0
4,4,12/18/2020,5666,7807,5666,7807,0.003,0,0,0.000,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,58,01/29/2021,11047,194651,9688,150114,0.056,1359,44537,0.017,...,169,31,15,1359,109,26,0,892,397,70
59,59,01/30/2021,6004,200655,4722,154836,0.057,1282,45819,0.017,...,122,86,184,1282,327,223,0,905,370,7
60,60,01/31/2021,1907,202562,1535,156371,0.058,372,46191,0.017,...,35,24,27,372,65,36,0,257,114,1
61,61,02/13/2021,10691,349505,7295,257977,0.096,3396,91528,0.034,...,678,863,468,3396,1863,793,0,2093,1126,177
62,62,02/14/2021,2811,352316,2370,260347,0.097,441,91969,0.034,...,45,18,4,440,46,9,0,309,132,0

In [6]:
sql_expr = """
SELECT *
FROM crime
"""

pd.read_sql(sql_expr, sqlite_engine)

,index,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,0,12014684,JD189901,03/17/2020 09:30:00 PM,039XX N LECLAIRE AVE,0820,THEFT,$500 AND UNDER,STREET,0,...,45.0,15.0,06,1141659.0,1925649.0,2020,03/25/2020 03:45:43 PM,41.952052,-87.754660,"(41.952051946, -87.754660372)"
1,1,12012127,JD189186,03/18/2020 02:03:00 AM,039XX W JACKSON BLVD,0910,MOTOR VEHICLE THEFT,AUTOMOBILE,APARTMENT,0,...,28.0,26.0,07,1150196.0,1898398.0,2020,03/25/2020 03:47:29 PM,41.877110,-87.723990,"(41.877110187, -87.723989719)"
2,2,12012330,JD189367,03/18/2020 08:50:00 AM,023XX N KEELER AVE,0560,ASSAULT,SIMPLE,RESIDENCE,0,...,35.0,20.0,08A,1147996.0,1915240.0,2020,03/25/2020 03:47:29 PM,41.923369,-87.731634,"(41.923368973, -87.731633833)"
3,3,12014760,JD192130,03/18/2020 01:00:00 PM,047XX W MONROE ST,1150,DECEPTIVE PRACTICE,CREDIT CARD FRAUD,OTHER (SPECIFY),0,...,28.0,25.0,11,1144749.0,1899145.0,2020,03/25/2020 03:47:29 PM,41.879264,-87.743971,"(41.879264422, -87.743970898)"
4,4,12012667,JD189808,03/18/2020 05:35:00 PM,003XX S CICERO AVE,2017,NARCOTICS,MANUFACTURE / DELIVER - CRACK,SIDEWALK,1,...,28.0,25.0,18,1144446.0,1898000.0,2020,03/25/2020 03:47:29 PM,41.876128,-87.745112,"(41.876128106, -87.745112291)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
209845,209845,12293111,JE141738,07/14/2020 02:00:00 AM,044XX W 59TH ST,0265,CRIMINAL SEXUAL ASSAULT,AGGRAVATED - OTHER,APARTMENT,0,...,13.0,62.0,02,NaN,NaN,2020,02/15/2021 03:50:56 PM,NaN,NaN,None
209846,209846,12293206,JE141667,12/04/2020 01:00:00 AM,039XX N HAMILTON AVE,0890,THEFT,FROM BUILDING,RESIDENCE,0,...,47.0,5.0,06,NaN,NaN,2020,02/15/2021 03:50:56 PM,NaN,NaN,None
209847,209847,12292823,JE141364,10/10/2020 12:00:00 PM,0000X E MONROE ST,0810,THEFT,OVER $500,APARTMENT,0,...,42.0,32.0,06,NaN,NaN,2020,02/15/2021 03:50:56 PM,NaN,NaN,None
209848,209848,12293190,JE141850,12/28/2020 12:01:00 AM,017XX W 48TH ST,2820,OTHER OFFENSE,TELEPHONE THREAT,APARTMENT,0,...,15.0,61.0,08A,NaN,NaN,2020,02/15/2021 03:50:56 PM,NaN,NaN,None
209849,209849,12292909,JE137656,12/17/2020 07:23:00 AM,053XX S PULASKI RD,1120,DECEPTIVE PRACTICE,FORGERY,BANK,0,...,23.0,62.0,10,NaN,NaN,2020,02/15/2021 03:50:56 PM,NaN,NaN,None